import {useState, useRef} from 'react';
import styles from "../../styles/website/Shop.module.css"
import Link from "next/link"
import Image from "next/image"
import {ArrowBackIosNewOutlined, SearchOutlined} from "@mui/icons-material";
import CategoryCard from "../../components/website/CategoryCard";
import axios from "axios";
import Head from "next/head";
import logo from "../../public/img/headerlogo.svg";
import {useSession} from "next-auth/react";
import {useSelector} from "react-redux";

const Shop = ({categories}) => {
    const [showDropdown, setShowDropdown] = useState(false);
    const [searchInput, setSearchInput] = useState("");
    const [filteredResults, setFilteredResults] = useState([]);
    const test = useRef(null);

    const {data: session} = useSession()
    const searchItems = (searchValue) => {
        setShowDropdown(true)
        setSearchInput(searchValue)
        const filteredData = inventory.filter((item)=>{
            return Object.values(item).join("").toLowerCase().includes(searchInput.toLowerCase())
        })
        setFilteredResults(filteredData)
    };

    const handleSearch = (e) => {
        setShowDropdown(false)
        setFilteredResults([])
        test.current.reset()

    };

    const handleSubmit = (e) => {
        e.preventDefault()
        console.log(e.target.value)

    };

    return (
        <div className={styles.container}>
        <div className={styles.header}>
            <div className={styles.backArrow}>
                <Link href="/shop">
                    <h1 className={styles.terug}><ArrowBackIosNewOutlined/> Terug</h1>
                </Link>
                </div>

            <h1>Choose a Category:</h1>

        </div>
            <Head>
                <title>RnG Diving</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


    <div className={styles.cardContainer}>

        {categories.map((category)=>(
            <CategoryCard key={category._id} fill='fill' index='all' category={category}/>
        ))}
    </div>

        </div>
    );
};

export default Shop;
Shop.layout = "L3";
export const getServerSideProps = async() => {
    const res = await axios.get(process.env.VERCEL_URL+`/api/catmenu`);
    return{
        props:{
            categories: res.data,

        }
    }
};
